# Generated by Django 5.2 on 2025-04-30 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ativo_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='grandeza_especialista_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('rotulo_normalidade', models.IntegerField(blank=True, default=0, null=True)),
                ('rotulo_transient', models.IntegerField(blank=True, default=0, null=True)),
                ('rotulo_steady_state', models.IntegerField(blank=True, default=0, null=True)),
                ('periodo_amostra_inicial_nao_rotulada', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='grandeza_industrial_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('um', models.CharField(blank=True, max_length=50, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('origem', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servidor_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='sonda_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='unidade_medida_padrao_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='uo_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='analise_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('exportacao_habilitada', models.BooleanField()),
                ('status_exportacao', models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Exportando', 'Exportando'), ('Exportada', 'Exportada'), ('Erro', 'Erro')], default='Pendente', max_length=15, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grandeza_especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf_app.grandeza_especialista_perf')),
            ],
        ),
        migrations.CreateModel(
            name='amostra_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('NORMAL', 'NORMAL'), ('TRANSIENT', 'TRANSIENT'), ('STEADY STATE', 'STEADY STATE'), ('UNKNOWN', 'UNKNOWN')], default='NORMAL', max_length=30)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf_app.analise_perf')),
            ],
        ),
        migrations.CreateModel(
            name='poco_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perf_app.ativo_perf')),
            ],
        ),
        migrations.AddField(
            model_name='analise_perf',
            name='poco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf_app.poco_perf'),
        ),
        migrations.AddField(
            model_name='analise_perf',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf_app.servidor_perf'),
        ),
        migrations.AddField(
            model_name='analise_perf',
            name='sonda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf_app.sonda_perf'),
        ),
        migrations.CreateModel(
            name='unidade_medida_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('coeficiente_angular', models.FloatField(blank=True, null=True)),
                ('coeficiente_linear', models.FloatField(blank=True, null=True)),
                ('unidade_medida_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perf_app.unidade_medida_padrao_perf')),
            ],
        ),
        migrations.AddField(
            model_name='ativo_perf',
            name='uo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perf_app.uo_perf'),
        ),
        migrations.CreateModel(
            name='relacao_especialista_industrial_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perf_app.grandeza_especialista_perf')),
                ('industrial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perf_app.grandeza_industrial_perf')),
            ],
            options={
                'unique_together': {('especialista', 'industrial')},
            },
        ),
        migrations.CreateModel(
            name='lookup_servidor_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf_app.servidor_perf')),
                ('sonda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf_app.sonda_perf')),
            ],
            options={
                'unique_together': {('sonda', 'servidor')},
            },
        ),
        migrations.CreateModel(
            name='variavel_industrial_perf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('grandeza_industrial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perf_app.grandeza_industrial_perf')),
                ('poco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perf_app.poco_perf')),
            ],
            options={
                'unique_together': {('grandeza_industrial', 'poco')},
            },
        ),
    ]
