# Generated by Django 5.2 on 2025-04-30 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='grandeza_especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('rotulo_normalidade', models.IntegerField(blank=True, default=0, null=True)),
                ('rotulo_transient', models.IntegerField(blank=True, default=0, null=True)),
                ('rotulo_steady_state', models.IntegerField(blank=True, default=0, null=True)),
                ('periodo_amostra_inicial_nao_rotulada', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='grandeza_industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='poco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('is_font_vip_xlsx', models.BooleanField(default=True)),
                ('is_not_font_vip_xlsx_date', models.DateTimeField(blank=True, null=True)),
                ('is_not_font_vip_xlsx_obs', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unidade_medida_padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='uo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('exportacao_habilitada', models.BooleanField()),
                ('status_exportacao', models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Exportando', 'Exportando'), ('Exportada', 'Exportada'), ('Erro', 'Erro')], default='Pendente', max_length=15, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grandeza_especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_app.grandeza_especialista')),
                ('poco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_app.poco')),
            ],
        ),
        migrations.CreateModel(
            name='amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('NORMAL', 'NORMAL'), ('TRANSIENT', 'TRANSIENT'), ('STEADY STATE', 'STEADY STATE'), ('UNKNOWN', 'UNKNOWN')], default='NORMAL', max_length=30)),
                ('estado_poco', models.CharField(choices=[('OPEN', 'OPEN'), ('SHUT-IN', 'SHUT-IN'), ('FLUSHING DIESEL', 'FLUSHING DIESEL'), ('FLUSHING GAS', 'FLUSHING GAS'), ('BULLHEADING', 'BULLHEADING'), ('CLOSED WITH DIESEL', 'CLOSED WITH DIESEL'), ('CLOSED WITH GAS', 'CLOSED WITH GAS'), ('RESTART', 'RESTART'), ('DEPRESSURIZATION', 'DEPRESSURIZATION'), ('UNKNOWN', 'UNKNOWN')], default='OPEN', max_length=30)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_app.analise')),
            ],
        ),
        migrations.CreateModel(
            name='uep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ueps_prod', to='prod_app.ativo')),
            ],
        ),
        migrations.AddField(
            model_name='poco',
            name='uep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_app.uep'),
        ),
        migrations.CreateModel(
            name='unidade_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('coeficiente_angular', models.FloatField(blank=True, null=True)),
                ('coeficiente_linear', models.FloatField(blank=True, null=True)),
                ('unidade_medida_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prod_app.unidade_medida_padrao')),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='uo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_app.uo'),
        ),
        migrations.CreateModel(
            name='relacao_especialista_industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_app.grandeza_especialista')),
                ('industrial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_app.grandeza_industrial')),
            ],
            options={
                'unique_together': {('especialista', 'industrial')},
            },
        ),
        migrations.CreateModel(
            name='variavel_industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_font_vip_api', models.BooleanField(default=True)),
                ('is_not_font_vip_api_date', models.DateTimeField(blank=True, null=True)),
                ('is_not_font_vip_api_obs', models.CharField(blank=True, max_length=300, null=True)),
                ('is_font_pi_system', models.BooleanField(blank=True, null=True)),
                ('is_not_font_pi_system_date', models.DateTimeField(blank=True, null=True)),
                ('is_not_font_pi_system_obs', models.CharField(blank=True, max_length=300, null=True)),
                ('is_af', models.BooleanField(blank=True, null=True)),
                ('servidor_pi', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=500, null=True)),
                ('grandeza_industrial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_app.grandeza_industrial')),
                ('poco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod_app.poco')),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prod_app.unidade_medida')),
            ],
            options={
                'unique_together': {('grandeza_industrial', 'poco')},
            },
        ),
    ]
